### ISSUE TITLE
Is there a way to sort the entries?

### ISSUE THREAD

**Issue by boospy** [theinvisible/tinyotp#1]
Hello, 

is there a way to sort the entries? I have 16 entries, and there is really a Mess in this list. I don't see through how sorting is done. Not by alphabet and also not by order how the entries are created. Cool would be a possibility to sort the entries themselves. 

Thanks a lot

**Comment by theinvisible** [comment]
Sorting is now enabled in Version 0.2.1, available in Git and Apt Repo
